/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lipassistant;

import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import jess.Fact;
import jess.JessException;
import jess.RU;
import jess.Rete;
import jess.Value;
import jess.ValueVector;
/**
 *
 * @author Tifani
 */
public class QuizFrame extends javax.swing.JFrame {
    Rete engine = new Rete();
    Fact fact;

    
    private int currentQuestion = 0;
    
    /**
     * Creates new form GameFrame
     */
    public QuizFrame() throws JessException {
        engine.clear();
        engine.reset();
        engine.batch("lipstickrules.clp");
        fact = new Fact("lipstick", engine);

        initComponents();
//        ImageIcon img = new ImageIcon(getClass().getResource("/werewolvesinwonderland/client/assets/icon_werewolf.png"));
//        this.setIconImage(img.getImage());
        this.setTitle("MLBB Lipstick Assistant");
        changeScreen("homePanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        Cat1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        quizPanel = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        btnChoice3 = new javax.swing.JButton();
        btnChoice2 = new javax.swing.JButton();
        btnChoice1 = new javax.swing.JButton();
        imgChoice3 = new javax.swing.JLabel();
        imgChoice2 = new javax.swing.JLabel();
        imgChoice1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        btnRestart = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExplanation = new javax.swing.JTextArea();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setMaximumSize(new java.awt.Dimension(960, 641));
        homePanel.setMinimumSize(new java.awt.Dimension(960, 641));
        homePanel.setPreferredSize(new java.awt.Dimension(960, 641));
        homePanel.setLayout(null);

        Cat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/cat.png"))); // NOI18N
        homePanel.add(Cat1);
        Cat1.setBounds(650, 250, 190, 330);

        jLabel2.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 86, 86));
        jLabel2.setText("Just answer a few questions...");
        homePanel.add(jLabel2);
        jLabel2.setBounds(120, 350, 670, 60);

        jLabel3.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 86, 86));
        jLabel3.setText("I will help you find the perfect MLBB");
        homePanel.add(jLabel3);
        jLabel3.setBounds(130, 180, 670, 60);

        jLabel4.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 86, 86));
        jLabel4.setText("(My Lips But Better) lipstick!");
        homePanel.add(jLabel4);
        jLabel4.setBounds(120, 240, 670, 60);

        btnStart.setBackground(java.awt.Color.white);
        btnStart.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        btnStart.setForeground(new java.awt.Color(239, 121, 121));
        btnStart.setText("Start");
        btnStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 121), 2));
        btnStart.setContentAreaFilled(false);
        btnStart.setFocusPainted(false);
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        homePanel.add(btnStart);
        btnStart.setBounds(130, 460, 210, 80);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/background.png"))); // NOI18N
        homePanel.add(bg);
        bg.setBounds(0, 0, 960, 641);

        mainPanel.add(homePanel, "homePanel");

        quizPanel.setLayout(null);

        lblQuestion.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(107, 86, 86));
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("Which form do you prefer?");
        quizPanel.add(lblQuestion);
        lblQuestion.setBounds(110, 170, 740, 60);

        btnChoice3.setBackground(java.awt.Color.white);
        btnChoice3.setFont(new java.awt.Font("Pacifico", 0, 24)); // NOI18N
        btnChoice3.setForeground(new java.awt.Color(239, 121, 121));
        btnChoice3.setText("Liquid");
        btnChoice3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 121), 2));
        btnChoice3.setContentAreaFilled(false);
        btnChoice3.setFocusPainted(false);
        btnChoice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChoice3MouseClicked(evt);
            }
        });
        btnChoice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoice3ActionPerformed(evt);
            }
        });
        quizPanel.add(btnChoice3);
        btnChoice3.setBounds(650, 290, 200, 70);

        btnChoice2.setBackground(java.awt.Color.white);
        btnChoice2.setFont(new java.awt.Font("Pacifico", 0, 24)); // NOI18N
        btnChoice2.setForeground(new java.awt.Color(239, 121, 121));
        btnChoice2.setText("Stick");
        btnChoice2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 121), 2));
        btnChoice2.setContentAreaFilled(false);
        btnChoice2.setFocusPainted(false);
        btnChoice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChoice2MouseClicked(evt);
            }
        });
        btnChoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoice2ActionPerformed(evt);
            }
        });
        quizPanel.add(btnChoice2);
        btnChoice2.setBounds(390, 290, 200, 70);

        btnChoice1.setBackground(java.awt.Color.white);
        btnChoice1.setFont(new java.awt.Font("Pacifico", 0, 24)); // NOI18N
        btnChoice1.setForeground(new java.awt.Color(239, 121, 121));
        btnChoice1.setText("Stick");
        btnChoice1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 121), 2));
        btnChoice1.setContentAreaFilled(false);
        btnChoice1.setFocusPainted(false);
        btnChoice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChoice1MouseClicked(evt);
            }
        });
        btnChoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoice1ActionPerformed(evt);
            }
        });
        quizPanel.add(btnChoice1);
        btnChoice1.setBounds(110, 290, 200, 70);

        imgChoice3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/liquid.png"))); // NOI18N
        quizPanel.add(imgChoice3);
        imgChoice3.setBounds(650, 380, 200, 200);

        imgChoice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/stick.png"))); // NOI18N
        quizPanel.add(imgChoice2);
        imgChoice2.setBounds(390, 380, 200, 200);

        imgChoice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/stick.png"))); // NOI18N
        quizPanel.add(imgChoice1);
        imgChoice1.setBounds(110, 380, 200, 200);

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/background.png"))); // NOI18N
        quizPanel.add(bg2);
        bg2.setBounds(0, 0, 960, 641);

        mainPanel.add(quizPanel, "quizPanel");

        resultPanel.setLayout(null);

        btnRestart.setBackground(java.awt.Color.white);
        btnRestart.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        btnRestart.setForeground(new java.awt.Color(239, 121, 121));
        btnRestart.setText("Restart");
        btnRestart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 121), 2));
        btnRestart.setContentAreaFilled(false);
        btnRestart.setFocusPainted(false);
        btnRestart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestartMouseClicked(evt);
            }
        });
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });
        resultPanel.add(btnRestart);
        btnRestart.setBounds(380, 490, 210, 80);

        lblResult.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        lblResult.setForeground(new java.awt.Color(239, 121, 121));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("NYX Soft Matte Lip Cream in Stockholm");
        resultPanel.add(lblResult);
        lblResult.setBounds(160, 230, 640, 70);

        jLabel6.setFont(new java.awt.Font("Pacifico", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 86, 86));
        jLabel6.setText("Your MLBB lipstick is...");
        resultPanel.add(jLabel6);
        jLabel6.setBounds(290, 170, 400, 60);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);

        txtExplanation.setColumns(20);
        txtExplanation.setFont(new java.awt.Font("Qlassik Medium", 0, 24)); // NOI18N
        txtExplanation.setLineWrap(true);
        txtExplanation.setRows(5);
        txtExplanation.setText("Neither lipstick nor lip gloss, this matte lip cream is a new kind of lip color that goes on silky smooth and sets to a matte finish. Soft Matte Lip Cream is surprisingly durable and unlike some matte lipstick formulas, also moisturizing");
        txtExplanation.setWrapStyleWord(true);
        txtExplanation.setBorder(null);
        txtExplanation.setFocusable(false);
        jScrollPane1.setViewportView(txtExplanation);

        resultPanel.add(jScrollPane1);
        jScrollPane1.setBounds(130, 320, 700, 130);

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/background.png"))); // NOI18N
        resultPanel.add(bg1);
        bg1.setBounds(0, 0, 960, 641);

        mainPanel.add(resultPanel, "resultPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked

    }//GEN-LAST:event_btnStartMouseClicked

    private void btnRestartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestartMouseClicked

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        changeScreen("homePanel");
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnChoice3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChoice3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoice3MouseClicked

    private void btnChoice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoice3ActionPerformed
        try {
            proceedQuiz(btnChoice3.getText());
        } catch (JessException ex) {
            Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChoice3ActionPerformed

    private void btnChoice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChoice1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChoice1MouseClicked

    private void btnChoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoice1ActionPerformed
        try {
            proceedQuiz(btnChoice1.getText());
        } catch (JessException ex) {
            Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChoice1ActionPerformed

    private void btnChoice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoice2ActionPerformed
        try {
            proceedQuiz(btnChoice2.getText());
        } catch (JessException ex) {
            Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChoice2ActionPerformed

    private void btnChoice2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChoice2MouseClicked
        
    }//GEN-LAST:event_btnChoice2MouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        startQuiz();
    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cat1;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JButton btnChoice1;
    private javax.swing.JButton btnChoice2;
    private javax.swing.JButton btnChoice3;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel imgChoice1;
    private javax.swing.JLabel imgChoice2;
    private javax.swing.JLabel imgChoice3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel quizPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JTextArea txtExplanation;
    // End of variables declaration//GEN-END:variables

    private void changeScreen(String screenName) {
        ((java.awt.CardLayout)mainPanel.getLayout()).show(mainPanel,screenName);
    }
    
    private void startQuiz() {
        currentQuestion = 1;
        lblQuestion.setText("Which form do you prefer?");
        btnChoice1.setText("Stick");
        changeImageChoice(1,"stick");
        btnChoice2.setVisible(false);
        imgChoice2.setVisible(false);
        btnChoice3.setText("Liquid");
        changeImageChoice(3,"liquid");
        changeScreen("quizPanel");
    }
    
    private void proceedQuiz(String answer) throws JessException {
        System.out.println(answer);
        if (currentQuestion==1) {
            //pref.setShape(answer);
            lblQuestion.setText("Which texture do you prefer?");
            if (answer.equals("Stick")) {
                fact.setSlotValue("shape", new Value("stick", RU.STRING));
                btnChoice1.setText("Matte");
                changeImageChoice(1,"matte");
                btnChoice2.setVisible(true);
                btnChoice2.setText("Creamy/Satin");
                changeImageChoice(2,"creamy");
                imgChoice2.setVisible(true);
                btnChoice3.setText("Sheer");
                changeImageChoice(3,"sheer");
            } else if (answer.equals("Liquid")) {
                fact.setSlotValue("shape", new Value(answer.toLowerCase(), RU.STRING));
                btnChoice1.setText("Matte");
                changeImageChoice(1,"matte");
                btnChoice2.setVisible(true);
                btnChoice2.setText("Glossy");
                changeImageChoice(2,"glossy");
                imgChoice2.setVisible(true);
                btnChoice3.setText("Stain");
                changeImageChoice(3,"stain");
            }
        } else if (currentQuestion==2) {
            fact.setSlotValue("texture", new Value(answer.toLowerCase(), RU.STRING));
            lblQuestion.setText("How much is your budget?");
            btnChoice1.setText("<100k");
            changeImageChoice(1,"100");
            btnChoice2.setText("100-200k");
            changeImageChoice(2,"200");
            btnChoice3.setText(">200k");
            changeImageChoice(3,"orangkaya");
        } else if (currentQuestion==3) {
            fact.setSlotValue("price", new Value(priceValue(answer), RU.STRING));
            lblQuestion.setText("What is your skintone?");
            btnChoice1.setText("Light");
            changeImageChoice(1,"light");
            btnChoice2.setText("Medium");
            changeImageChoice(2,"medium");
            btnChoice3.setText("Dark");
            changeImageChoice(3,"dark");
        } else if (currentQuestion==4) {
            fact.setSlotValue("skintone", new Value(answer.toLowerCase(), RU.STRING));
            engine.assertFact(fact);
            endQuiz();
        }
        currentQuestion++;
    }
    
    private void endQuiz() throws JessException {
        engine.eval("(focus recommend)");
        engine.eval("(run)");
        
        String result = "";
        String explanation = "";
        
        Iterator it = engine.listFacts();
        while (it.hasNext()) {
            Fact fact = (Fact) it.next();
            if (fact.getName().equals("MAIN::recommendation")){
                result = fact.getSlotValue("name").toString();
                explanation = fact.getSlotValue("explanation").toString();
            }
                
        }
        
        lblResult.setText(result);
        txtExplanation.setText(explanation);
        changeScreen("resultPanel");
    }
    
    private void changeImageChoice(int no, String image) {
        if (no==1) {
            imgChoice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/"+image+".png")));
        } else if (no==2) {
            imgChoice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/"+image+".png")));
        } else if (no==3) {
            imgChoice3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lipassistant/assets/"+image+".png")));
        }
    }
    
    private String priceValue(String answer){
        if (answer.equals("<100k")){
            return "a";
        }
        else if (answer.equals("100-200k")){
            return "b";
        }
        else if (answer.equals(">200k")){
            return "c";
        }
        else {
            return "a";
        }
    }
   
    
    

}
